services:
  jboss610:
    image: reajason/jboss:6-jdk7
    container_name: jboss610
    ports:
      - 8080:8080
      - 5005:5005
    environment:
      JAVA_OPTS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005
    volumes:
      - ../../../vul/vul-webapp/build/libs/vul-webapp.war:/usr/local/jboss/server/jbossweb-standalone/deploy/app.war
