name: Test

on:
  push:
    paths-ignore:
      - 'docs/**'
      - 'boot/**'
      - 'web/**'
      - '**.md'
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  integration-test:
    strategy:
      fail-fast: false
      matrix:
        middleware: [ "websphere"]
    runs-on: ubuntu-latest
    name: ${{ matrix.middleware }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Integration Test with gradle
        run: ./gradlew :integration-test:test --tests '*.${{ matrix.middleware }}.*' --info
      - name: Export Integration Test Summary
        run: cat integration-test/build/test-results/report.md >> $GITHUB_STEP_SUMMARY
      - name: Upload jacoco
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.middleware }}-integration-test
          path: integration-test/build/jacoco/test.exec
          retention-days: 1